name: Auto assignment

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: "Auto-assign"
        uses: pozil/auto-assign-issue@v2
        secrets:
          access-token: ${{ secrets.GH_TOKEN }}
        with:
          teams: charades-team
          allowSelfAssign: false
