name: Auto PR assignment

on:
  pull_request:
    types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Auto-assign"
        token: ${{ secrets.GH_TOKEN }}
        uses: pozil/auto-assign-issue@v2
        with:
          org: Skkkra
          teams: charades-team
          allowSelfAssign: false
