name: Auto assignment

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Auto-assign"
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          teams: charades-team
          allowSelfAssign: false
