name: Auto PR assignment

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Auto-assign"
        uses: pozil/auto-assign-issue@v2
        with:
          read: Skkkra
          teams: charades-team
          allowSelfAssign: false
