name: Auto assignment

on:
  [push]
  # pull_request:
  #   types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: "Auto-assign "
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          teams: charades-team
          allowSelfAssign: false
