name: Charades UI Build

on:
  push:
    paths:
      - ./charades-ui/**

jobs:
  build:
    strategy:
      matrix:
        node-version: ["20.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Monorepo install
        uses: ./.github/actions/yarn
        with:
          cwd: "./charades-ui"
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true
